# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testcodel
    username: root
    password: abcde
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml